### PR TITLE
Added Simple High Profile 3D Printed Case

### PR DESCRIPTION
**Pull request by jmo808**
Added a 3D Printed Case Directory and put a simple high profile case pre split for most ~200x200 printers.

### CODE REVIEW

**Comment by jmo808** [comment]
One more comment, is that this case is designed to use the half shield .dxf acrylic window.

**Comment by dsanchezseco** [comment]
Can you add a README on the folder with the case info/assembly and such?

Add a "designed by" too to take the credit yourself

**Comment by jmo808** [comment]
> 
> 
> Can dd a README on the folder with the case info/assembly and such?
> 
> Add a "designed by" too to take the credit yourself

I was just thinking that I was missing a README for assembly. I'll close this PR and re-submit.

**Comment by dsanchezseco** [comment]
you can update your branch and it will update the pr too, no need for a different pr

**Comment by jmo808** [comment]
I added a README with some fairly detailed assembly instructions and some pics as well.

**Comment by dsanchezseco** [comment]
Thanks awesome job, I hope you enjoy your keeb!! Glad you like it enough to build it and add a case!! :)

**Comment by jmo808** [comment]
> 
> 
> Thanks awesome job, I hope you enjoy your keeb!! Glad you like it enough to build it and add a case!! :)

It's a great design! What the XD75 should have been... I have a few more case designs for this board coming.

**Pull request merged**
